/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.controlador;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GW-03
 */
public class busqueda extends javax.swing.JFrame {

    /**
     * Creates new form busqueda
     */
    private String institucion;
    public static final String FILTRAR = "FILTRAR";

    public busqueda(String institucion) {
        initComponents();
        this.institucion = institucion;
        this.setLocationRelativeTo(null);
        
    }

    public void ejecutar() {
        this.setVisible(true);
    }
    
    
    public void cargarListaPagos(ArrayList<String[]> lista){
        DefaultTableModel pagos = new DefaultTableModel();
        pagos.addColumn("n_recibo");
        pagos.addColumn("concepto");
        pagos.addColumn("cajero");
        pagos.addColumn("fechacobro");
        pagos.addColumn("legajo");
        pagos.addColumn("formapago");
        pagos.addColumn("anio");
        pagos.addColumn("nivel");
        pagos.addColumn("Curso");
        pagos.addColumn("supago");
      
        
        
       for(String[] fila : lista ){
            pagos.addRow(fila);
        }        
        tablaPagos.setModel(pagos);
    }

    public String getInstitucion() {
        return institucion;
    }

    public void setInstitucion(String institucion) {
        this.institucion = institucion;
    }

    public void setControlador(controlador control) {
        btnFiltrar.setActionCommand(FILTRAR);
        btnFiltrar.addActionListener(control);

    }

    public String getNivel() {
        return cbxNivel.getSelectedItem().toString();
    }
    
     public String getConcepto() {
        return cbxConcepto.getSelectedItem().toString();
    }
    
     public void setNivel(int nivel) {
        cbxNivel.setSelectedIndex(nivel);
     
    }

    public String getDesde() {
        Date date = Desde.getDate();
       
        long d = date.getTime();
        java.sql.Date fecha = new java.sql.Date(d);
        String f = fecha.toString();
       
        return f;
    }

    public String getHasta() {
        Date date = Hasta.getDate();
       
        long d = date.getTime();
        java.sql.Date fecha = new java.sql.Date(d);
        String f = fecha.toString();
       
        return f;
    }

   

    public void setTotal(double Total) {
       DecimalFormat f1 = new DecimalFormat("#.00");
       String t = f1.format(Total);
       txtTotal.setText(t);
    }
    
     public void setTotalLineas(int t) {
       
       labelTotalLineas.setText(""+t);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxNivel = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPagos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnFiltrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cbxConcepto = new javax.swing.JComboBox<>();
        Desde = new com.toedter.calendar.JDateChooser();
        Hasta = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        labelTotalLineas = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "INICIAL", "PRIMARIO", "SECUNDARIO", "TERCIARIO" }));
        getContentPane().add(cbxNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 11, 130, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nivel :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, 34, -1));

        tablaPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaPagos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 93, 1040, 450));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Desde: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Hasta:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        btnFiltrar.setText("Filtrar");
        getContentPane().add(btnFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 130, 30));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 560, 50, 30));

        txtTotal.setEditable(false);
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 560, 150, 30));

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 560, 160, 40));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Concepto: ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 60, 20));

        cbxConcepto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "MATRICULA", "SEGURO", "CUOTAS", "OTROS" }));
        getContentPane().add(cbxConcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 140, -1));
        getContentPane().add(Desde, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 130, -1));
        getContentPane().add(Hasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 140, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total Pagos en Lista :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 600, 140, -1));

        labelTotalLineas.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(labelTotalLineas, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 600, 70, 20));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/textura-madera-en-negro_2560x1600_xtrafondos.com.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 630));

        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 600, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new busqueda("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Desde;
    private com.toedter.calendar.JDateChooser Hasta;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JComboBox<String> cbxConcepto;
    private javax.swing.JComboBox<String> cbxNivel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTotalLineas;
    private javax.swing.JTable tablaPagos;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
