/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.controlador;
import java.awt.Color;

/**
 *
 * @author GW-03
 */
public class Principal extends javax.swing.JFrame {

    public static final String WASHINGTON="WASHINGTON";
    public static final String SANFER="SANFER";
    public static final String SANTO="SANTO DOMINGO";
    public static final String NORTE="NORTE ARGENTINO";
    public static final String ANEXO="MATE DE LUNA";
    public static final String FAMAILLA="FAMAILLA";
    public static final String SECUNDARIO="IPEF SECUNDARIO";
    
    public Principal() {
        initComponents();
        this.setTitle("SISTEMA COSTOS");
        this.setLocationRelativeTo(null);
       
    }
    
    public void ejecutar(){
        this.setVisible(true);
    }
    
    
    public void setControlador(controlador control){
       btnWashington.setActionCommand(WASHINGTON);
       btnWashington.addActionListener(control);
       
       btnSanfer.setActionCommand(SANFER);
       btnSanfer.addActionListener(control);
       
       btnSD.setActionCommand(SANTO);
       btnSD.addActionListener(control);
       
       btnNorte.setActionCommand(NORTE);
       btnNorte.addActionListener(control);
       
       btnAnexo.setActionCommand(ANEXO);
       btnAnexo.addActionListener(control);
       
       btnFamailla.setActionCommand(FAMAILLA);
       btnFamailla.addActionListener(control);
       
       btnSecundario.setActionCommand(SECUNDARIO);
       btnSecundario.addActionListener(control);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnWashington = new javax.swing.JButton();
        btnSanfer = new javax.swing.JButton();
        btnSD = new javax.swing.JButton();
        btnNorte = new javax.swing.JButton();
        btnAnexo = new javax.swing.JButton();
        btnFamailla = new javax.swing.JButton();
        btnSecundario = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 311, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Famailla");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Washington");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 100, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Mate de Luna");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("San Fernando");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Norte Argentino");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Santo Domingo");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Seleccione la institucion");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 21));

        btnWashington.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Washington.png"))); // NOI18N
        btnWashington.setContentAreaFilled(false);
        btnWashington.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnWashingtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnWashingtonMouseExited(evt);
            }
        });
        btnWashington.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWashingtonActionPerformed(evt);
            }
        });
        getContentPane().add(btnWashington, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 150, 150));

        btnSanfer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SANFERNANDO.png"))); // NOI18N
        btnSanfer.setContentAreaFilled(false);
        btnSanfer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSanferMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSanferMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSanferMousePressed(evt);
            }
        });
        getContentPane().add(btnSanfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 160, 150));

        btnSD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Santo domingo.png"))); // NOI18N
        btnSD.setContentAreaFilled(false);
        btnSD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSDMouseExited(evt);
            }
        });
        getContentPane().add(btnSD, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 160, 150));

        btnNorte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IPEF.png"))); // NOI18N
        btnNorte.setContentAreaFilled(false);
        btnNorte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNorteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNorteMouseExited(evt);
            }
        });
        getContentPane().add(btnNorte, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 150, 140));

        btnAnexo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IPEF.png"))); // NOI18N
        btnAnexo.setContentAreaFilled(false);
        btnAnexo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAnexoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAnexoMouseExited(evt);
            }
        });
        getContentPane().add(btnAnexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 160, 140));

        btnFamailla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IPEF.png"))); // NOI18N
        btnFamailla.setContentAreaFilled(false);
        btnFamailla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFamaillaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFamaillaMouseExited(evt);
            }
        });
        getContentPane().add(btnFamailla, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 160, 140));

        btnSecundario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IPEF.png"))); // NOI18N
        btnSecundario.setContentAreaFilled(false);
        btnSecundario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSecundarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSecundarioMouseExited(evt);
            }
        });
        btnSecundario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSecundarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnSecundario, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 130, 140));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Secundario");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/textura-madera-en-negro_2560x1600_xtrafondos.com.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnWashingtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWashingtonMouseEntered
        btnWashington.setBorder(javax.swing.BorderFactory.createLineBorder(Color.WHITE));
    }//GEN-LAST:event_btnWashingtonMouseEntered

    private void btnWashingtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWashingtonMouseExited
       btnWashington.setBorder(null); // TODO add your handling code here:
    }//GEN-LAST:event_btnWashingtonMouseExited

    private void btnSanferMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSanferMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSanferMousePressed

    private void btnSanferMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSanferMouseEntered
       btnSanfer.setBorder(javax.swing.BorderFactory.createLineBorder(Color.WHITE)); // TODO add your handling code here:
    }//GEN-LAST:event_btnSanferMouseEntered

    private void btnSanferMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSanferMouseExited
btnSanfer.setBorder(null);        // TODO add your handling code here:
    }//GEN-LAST:event_btnSanferMouseExited

    private void btnSDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSDMouseEntered
btnSD.setBorder(javax.swing.BorderFactory.createLineBorder(Color.WHITE));        // TODO add your handling code here:
    }//GEN-LAST:event_btnSDMouseEntered

    private void btnSDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSDMouseExited
btnSD.setBorder(null);        // TODO add your handling code here:
    }//GEN-LAST:event_btnSDMouseExited

    private void btnNorteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNorteMouseEntered
btnNorte.setBorder(javax.swing.BorderFactory.createLineBorder(Color.WHITE));        // TODO add your handling code here:
    }//GEN-LAST:event_btnNorteMouseEntered

    private void btnNorteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNorteMouseExited
btnNorte.setBorder(null);        // TODO add your handling code here:
    }//GEN-LAST:event_btnNorteMouseExited

    private void btnAnexoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnexoMouseEntered
btnAnexo.setBorder(javax.swing.BorderFactory.createLineBorder(Color.WHITE));        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnexoMouseEntered

    private void btnAnexoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnexoMouseExited
btnAnexo.setBorder(null);        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnexoMouseExited

    private void btnFamaillaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFamaillaMouseEntered
btnFamailla.setBorder(javax.swing.BorderFactory.createLineBorder(Color.WHITE));        // TODO add your handling code here:
    }//GEN-LAST:event_btnFamaillaMouseEntered

    private void btnFamaillaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFamaillaMouseExited
btnFamailla.setBorder(null);        // TODO add your handling code here:
    }//GEN-LAST:event_btnFamaillaMouseExited

    private void btnSecundarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSecundarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSecundarioActionPerformed

    private void btnSecundarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSecundarioMouseEntered
       btnSecundario.setBorder(javax.swing.BorderFactory.createLineBorder(Color.WHITE));        // TODO add your handling code here:
     // TODO add your handling code here:
    }//GEN-LAST:event_btnSecundarioMouseEntered

    private void btnSecundarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSecundarioMouseExited
btnSecundario.setBorder(null);        // TODO add your handling code here:
    }//GEN-LAST:event_btnSecundarioMouseExited

    private void btnWashingtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWashingtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnWashingtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnexo;
    private javax.swing.JButton btnFamailla;
    private javax.swing.JButton btnNorte;
    private javax.swing.JButton btnSD;
    private javax.swing.JButton btnSanfer;
    private javax.swing.JButton btnSecundario;
    private javax.swing.JButton btnWashington;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
